//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Rezultati
{
    using System;
    using System.Collections.Generic;
    
    public partial class Utakmica
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Utakmica()
        {
            this.UcinakIgracas = new HashSet<UcinakIgraca>();
        }
    
        public int UtakmicaId { get; set; }
        public System.DateTime DatumIgranja { get; set; }
        public int KoloId { get; set; }
        public int DomaciTimId { get; set; }
        public int GostujuciTimId { get; set; }
        public Nullable<int> BrojGolovaDomacina { get; set; }
        public Nullable<int> BrojGolovaGostujuceg { get; set; }
        public bool Odigrana { get; set; }
    
        public virtual Kolo Kolo { get; set; }
        public virtual Tim Tim { get; set; }
        public virtual Tim TimGost { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<UcinakIgraca> UcinakIgracas { get; set; }
    }
}
